name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.mirrors.jibril.us", custom_domain = true },
  { pattern = "quey.mirrors.jibril.us", custom_domain = true },
  { pattern = "gcr.mirrors.jibril.us", custom_domain = true },
  { pattern = "k8s-gcr.mirrors.jibril.us", custom_domain = true },
  { pattern = "k8s.mirrors.jibril.us", custom_domain = true },
  { pattern = "ghcr.mirrors.jibril.us", custom_domain = true },
  { pattern = "cloudsmith.mirrors.jibril.us", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
